// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_SfzhQZo261Z3kBvxNEz2zY1gzKAQ274',
    appId: '1:162707233969:web:04d90b8885ba8768999690',
    messagingSenderId: '162707233969',
    projectId: 'isa-citra-1691878861005',
    authDomain: 'isa-citra-1691878861005.firebaseapp.com',
    storageBucket: 'isa-citra-1691878861005.appspot.com',
    measurementId: 'G-ERVNNYPQ3L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHbEAH0oRBVHMBkaZCvNWoRZkN8xnvB6I',
    appId: '1:162707233969:android:44629712831a8608999690',
    messagingSenderId: '162707233969',
    projectId: 'isa-citra-1691878861005',
    storageBucket: 'isa-citra-1691878861005.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4XHrPxIBsA4Nf0NJK-tLzH3WKSNtPSjU',
    appId: '1:162707233969:ios:3015412900cda2e8999690',
    messagingSenderId: '162707233969',
    projectId: 'isa-citra-1691878861005',
    storageBucket: 'isa-citra-1691878861005.appspot.com',
    iosBundleId: 'com.example.bookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4XHrPxIBsA4Nf0NJK-tLzH3WKSNtPSjU',
    appId: '1:162707233969:ios:3015412900cda2e8999690',
    messagingSenderId: '162707233969',
    projectId: 'isa-citra-1691878861005',
    storageBucket: 'isa-citra-1691878861005.appspot.com',
    iosBundleId: 'com.example.bookingApp',
  );
}
